#include<stdio.h>

int main()
{
    int m,num,i;
    int a=0;
    while(scanf("%d",&num)!=EOF)
    {
        if(num==0)
        {
            continue;
        }
        for(i=0;i<num;i++)
        {
            scanf("%d",&m);
        while(m>=100)
        {
            a=a+m/100;
            m=m%100;
            break;
        }
        if(m>=50)
        {
            a+=1;
            m-=50;
            while(m>=10)
            {
                a=a+m/10;
                m=m%10;
            }
            if(m>=5)
            {
                a+=1;
                m-=5;
                a+=1;
                m-=5;
                if(m==1||m==2)
                a+=1;
                if(m==3||m==4)
                a+=2;
            }
            else
            {
                if(m==1||m==2)
                a+=1;
                if(m==3||m==4)
                a+=2;
            }
        }
        else
        {
          while(m>=10)
            {
                a=a+m/10;
                m=m%10;
            }
           if(m>=5)
           {
                a+=1;
                m-=5;
                if(m==1||m==2)
                a+=1;
                if(m==3||m==4)
                a+=2;
            }
            else
            {
                if(m==1||m==2)
                a+=1;
                if(m==3||m==4)
                a+=2;
            } 
        }   
        }
        printf("%d\n",a);
        a=0;
    }
}
